package io.enigmaclient.host;

import io.canvasmc.canvas.distributed.config.EnigmaDistributedConfig;
import io.enigmaclient.EnigmaClient;
import io.enigmaclient.config.EnigmaConfig;
import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Managed einen EnigmaEngine COMPUTE_HOST als Sidecar-Prozess: Der Spieler bleibt in seinem
 * normalen Spiel, w\u00e4hrend im Hintergrund eine eigene EnigmaEngine-Serverinstanz gestartet
 * wird, die sich outbound mit dem konfigurierten World Host verbindet und Regionen ausf\u00fchrt.
 */
public final class ComputeHostService {

    public enum State { STOPPED, RESTARTING, STARTING, WAITING, CONNECTED, ERROR }

    public static final String DIR_NAME = "enigma-compute-host";

    private static final String MARK_CONNECTED = "Registered with World Host";
    private static final String MARK_LOST = "Connection to the World Host was lost";
    private static final String MARK_ATTEMPT = "Starting EnigmaEngine as COMPUTE_HOST";
    private static final String MARK_REJECTED = "World Host rejected handshake";

    private static final long RESTART_DELAY_MS = 10_000L;
    private static final long RETRY_DELAY_MS = 30_000L;
    private static final long STARTING_WINDOW_MS = 45_000L;
    private static final long FAST_DEATH_MS = 60_000L;
    private static final int MAX_FAST_DEATHS = 3;

    private static final int RC_PORT = 25577;
    private static final long STATS_INTERVAL_MS = 5_000L;
    private static final long STATS_BACKOFF_MS = 15_000L;
    private static final int RC_TIMEOUT_MS = 2_500;

    private static final String SERVER_PROPERTIES = """
            # Generated by EnigmaClient (Compute-Host Sidecar) - kann angepasst werden.
            level-type=minecraft\\:flat
            generate-structures=false
            max-players=1
            view-distance=4
            simulation-distance=4
            spawn-protection=0
            online-mode=false
            allow-nether=false
            enable-command-block=false
            motd=Enigma Compute Host
            server-ip=127.0.0.1
            server-port=25566
            """;

    private static ComputeHostService instance;

    private final ScheduledExecutorService executor;
    private final Path dir;
    private final Path consoleLog;
    private final AtomicBoolean stopping = new AtomicBoolean(false);

    private volatile Process process;
    private volatile long startedAtMs;
    private volatile long nextActionAtMs;
    private volatile long connectedSinceMs;
    private volatile long logOffset;
    private volatile int restarts;
    private volatile int rapidDeaths;
    private volatile int lastExitCode = Integer.MIN_VALUE;
    private volatile boolean sessionActive;
    private volatile boolean jarMissing;
    private volatile String lastError;
    private volatile String lastNotifiedError;
    private volatile DistributedStatus stats;
    private long nextStatsAtMs;

    private boolean wasConnected;
    private int ticks;

    private ComputeHostService(Path dir) {
        this.dir = dir;
        this.consoleLog = dir.resolve("console.log");
        this.executor = Executors.newSingleThreadScheduledExecutor(r -> {
            Thread thread = new Thread(r, "EnigmaComputeHost");
            thread.setDaemon(true);
            return thread;
        });
    }

    public static synchronized void init() {
        if (instance != null) {
            return;
        }
        Path dir = FabricLoader.getInstance().getGameDir().resolve(DIR_NAME);
        instance = new ComputeHostService(dir);
        instance.executor.scheduleWithFixedDelay(instance::superviseSafely, 1, 1, TimeUnit.SECONDS);
        if (EnigmaClient.config != null && EnigmaClient.config.enabled) {
            instance.start();
        }
    }

    public static ComputeHostService get() {
        return instance;
    }

    /** Wird vom Shutdown-Hook des Clients aufgerufen: stoppt den Sidecar blockierend. */
    public static void shutdown() {
        ComputeHostService service = instance;
        if (service == null) {
            return;
        }
        service.sessionActive = false;
        service.stopBlocking(12_000L);
        service.executor.shutdownNow();
    }

    public void start() {
        sessionActive = true;
        lastError = null;
        lastNotifiedError = null;
        rapidDeaths = 0;
        restarts = 0;
        executor.submit(() -> {
            nextActionAtMs = 0L;
            launchIfDue();
        });
        EnigmaClient.notifyUser("Compute-Host wird gestartet \u2026", true);
    }

    public void stop() {
        sessionActive = false;
        executor.submit(this::stopGracefully);
    }

    public void restart() {
        sessionActive = true;
        lastError = null;
        lastNotifiedError = null;
        rapidDeaths = 0;
        restarts = 0;
        executor.submit(() -> {
            stopGracefully();
            nextActionAtMs = 0L;
            launchIfDue();
        });
        EnigmaClient.notifyUser("Compute-Host wird neu gestartet \u2026", true);
    }

    public void toggle() {
        if (sessionActive) {
            stop();
        } else {
            start();
        }
    }

    public boolean isSessionActive() {
        return sessionActive;
    }

    public State state() {
        Process current = process;
        if (current != null && current.isAlive()) {
            if (connectedSinceMs != 0L) {
                return State.CONNECTED;
            }
            return System.currentTimeMillis() - startedAtMs < STARTING_WINDOW_MS
                    ? State.STARTING
                    : State.WAITING;
        }
        if (lastError != null) {
            return State.ERROR;
        }
        if (sessionActive) {
            return State.RESTARTING;
        }
        return State.STOPPED;
    }

    public String stateText() {
        switch (state()) {
            case CONNECTED:
                return "Verbunden \u00B7 seit " + EnigmaClient.formatDuration(
                        System.currentTimeMillis() - connectedSinceMs);
            case STARTING:
                return "Startet \u2026";
            case WAITING:
                return "Verbindet \u2026";
            case RESTARTING:
                return "Startet neu in " + restartsIn() + " s \u2026";
            case ERROR:
                return "Fehler: " + lastError;
            default:
                return "Gestoppt";
        }
    }

    public long uptimeMillis() {
        long started = startedAtMs;
        return started == 0L ? 0L : System.currentTimeMillis() - started;
    }

    public int restarts() {
        return restarts;
    }

    public long restartsIn() {
        return Math.max(0L, nextActionAtMs - System.currentTimeMillis()) / 1000L;
    }

    public int lastExitCode() {
        return lastExitCode;
    }

    public boolean jarMissing() {
        return jarMissing;
    }

    public String lastError() {
        return lastError;
    }

    public Path dir() {
        return dir;
    }

    public Path jarPath() {
        return resolveJar(EnigmaClient.config);
    }

    public DistributedStatus stats() {
        return stats;
    }

    private void superviseSafely() {
        try {
            supervise();
        } catch (Throwable t) {
            EnigmaClient.LOGGER.error("Compute-Host-Supervisor fehlgeschlagen: {}", t.toString());
        }
    }

private void supervise() {
        long now = System.currentTimeMillis();
    Process current = process;

    if (current != null && !current.isAlive()) {
        lastExitCode = current.exitValue();
        long uptime = now - startedAtMs;
        process = null;
        connectedSinceMs = 0L;
        stats = null;
        wasConnected = false;
        if (stopping.get()) {
            // Stoppvorgang l\u00e4uft - stopGracefully r\u00e4umt auf.
        } else if (sessionActive) {
            if (uptime < FAST_DEATH_MS) {
                rapidDeaths++;
            } else {
                rapidDeaths = 0;
            }
            if (rapidDeaths >= MAX_FAST_DEATHS) {
                sessionActive = false;
                lastError = "Prozess st\u00fcrzt wiederholt ab (Exit " + lastExitCode
                        + ") - Start pausiert";
                notifyError();
            } else {
                restarts++;
                nextActionAtMs = now + RESTART_DELAY_MS;
                EnigmaClient.notifyUser(
                        "Compute-Host beendet (Exit " + lastExitCode + ") - Neustart in "
                                + RESTART_DELAY_MS / 1000L + " s", true);
            }
        } else {
            EnigmaClient.LOGGER.info("Compute-Host beendet (Exit {})", lastExitCode);
        }
    }

    if (++ticks % 5 == 0) {
        Process alive = process;
        if (alive != null && alive.isAlive()) {
            scanConsole();
        }
    }

    if (connectedSinceMs != 0L && process != null && process.isAlive() && now >= nextStatsAtMs) {
        pollStats(now);
    }

    if (sessionActive && !stopping.get() && process == null && now >= nextActionAtMs) {
        launchIfDue();
    }
}

    private void launchIfDue() {
        EnigmaConfig config = EnigmaClient.config;
        if (config == null) {
            return;
        }

        Path jar;
        try {
            jar = resolveJar(config);
        } catch (Exception e) {
            setError("Ung\u00fcltiger Jar-Pfad: " + config.jarPath);
            nextActionAtMs = System.currentTimeMillis() + RETRY_DELAY_MS;
            return;
        }

        if (!Files.isRegularFile(jar)) {
            jarMissing = true;
            setError("EnigmaEngine.jar nicht gefunden: " + jar);
            nextActionAtMs = System.currentTimeMillis() + RETRY_DELAY_MS;
            return;
        }
        jarMissing = false;

        try {
            validateDistributedConfig(config);
        } catch (IllegalStateException e) {
            setError("Ung\u00fcltige Distributed-Konfiguration: " + e.getMessage());
            nextActionAtMs = System.currentTimeMillis() + RETRY_DELAY_MS;
            return;
        }

        try {
            prepareDir();
        } catch (IOException e) {
            setError("Verzeichnis konnte nicht vorbereitet werden: " + e);
            nextActionAtMs = System.currentTimeMillis() + RETRY_DELAY_MS;
            return;
        }

        List<String> command = new ArrayList<>();
        command.add(javaBinary());
        command.add("-Xmx" + config.xmxMb + "M");
        command.add("-Denigma.distributed.enabled=true");
        command.add("-Denigma.distributed.role=COMPUTE_HOST");
        command.add("-Denigma.distributed.worldHost=" + config.host);
        command.add("-Denigma.distributed.worldHostPort=" + config.port);
        command.add("-Denigma.distributed.debugLogging=" + (config.debugLogging ? "true" : "false"));
        command.add("-jar");
        command.add(jar.toAbsolutePath().toString());
        command.add("nogui");

        try {
            ProcessBuilder builder = new ProcessBuilder(command)
                    .directory(dir.toFile())
                    .redirectErrorStream(true)
                    .redirectOutput(ProcessBuilder.Redirect.appendTo(consoleLog.toFile()));
            process = builder.start();
            startedAtMs = System.currentTimeMillis();
            lastError = null;
            lastNotifiedError = null;
            connectedSinceMs = 0L;
            stats = null;
            nextStatsAtMs = 0L;
            wasConnected = false;
            EnigmaClient.LOGGER.info("Compute-Host gestartet: {}", String.join(" ", command));
            EnigmaClient.notifyUser(
                    "Compute-Host gestartet (Xmx " + config.xmxMb + " MB, Ziel " + config.target() + ")",
                    true);
        } catch (IOException e) {
            setError("Start fehlgeschlagen: " + e);
            nextActionAtMs = System.currentTimeMillis() + RETRY_DELAY_MS;
        }
    }

    /**
     * Spiegelt die Mod-Konfiguration in die eingebettete Enigma-Konfiguration und laesst deren
     * felduebergreifende Regeln greifen, bevor der Sidecar gestartet wird.
     */
    private void validateDistributedConfig(EnigmaConfig config) {
        EnigmaDistributedConfig distributed = new EnigmaDistributedConfig();
        distributed.enabled = true;
        distributed.role = "COMPUTE_HOST";
        distributed.worldHostAddress = config.host;
        distributed.port = config.port;
        distributed.worldHostPort = config.port;
        distributed.debugLogging = config.debugLogging;
        distributed.validateCrossField();
    }

    private void stopGracefully() {
        if (!stopping.compareAndSet(false, true)) {
            return;
        }
        Process current = process;
        try {
            if (current != null && current.isAlive()) {
                EnigmaClient.LOGGER.info("Compute-Host wird gestoppt \u2026");
                sendStop(current);
                if (!waitForQuietly(current, 20_000L)) {
                    destroyTree(current, false);
                    if (!waitForQuietly(current, 5_000L)) {
                        destroyTree(current, true);
                    }
                }
            }
        } catch (Exception e) {
            EnigmaClient.LOGGER.warn("Stop des Compute-Hosts fehlgeschlagen: {}", e.toString());
        } finally {
            if (current != null && current.isAlive()) {
                destroyTree(current, true);
            }
            process = null;
            connectedSinceMs = 0L;
            stats = null;
            wasConnected = false;
            stopping.set(false);
        }
        EnigmaClient.notifyUser("Compute-Host gestoppt", true);
    }

    private void stopBlocking(long graceMs) {
        Process current = process;
        if (current == null || !current.isAlive()) {
            process = null;
            return;
        }
        if (stopping.get()) {
            long deadline = System.currentTimeMillis() + graceMs;
            while (current.isAlive() && System.currentTimeMillis() < deadline) {
                try {
                    Thread.sleep(100L);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
            if (current.isAlive()) {
                destroyTree(current, true);
            }
            return;
        }
        stopping.set(true);
        try {
            sendStop(current);
            if (!waitForQuietly(current, graceMs)) {
                destroyTree(current, false);
                if (!waitForQuietly(current, 3_000L)) {
                    destroyTree(current, true);
                }
            }
        } finally {
            if (current.isAlive()) {
                destroyTree(current, true);
            }
            stopping.set(false);
        }
    }

    private void scanConsole() {
        try {
            if (!Files.isRegularFile(consoleLog)) {
                return;
            }
            long size = Files.size(consoleLog);
            if (size < logOffset) {
                logOffset = 0L;
            }
            if (size == logOffset) {
                return;
            }
            int toRead = (int) Math.min(size - logOffset, 1024L * 1024L);
            byte[] buffer = new byte[toRead];
            try (InputStream in = Files.newInputStream(consoleLog)) {
                skipFully(in, logOffset);
                int offset = 0;
                while (offset < buffer.length) {
                    int read = in.read(buffer, offset, buffer.length - offset);
                    if (read < 0) {
                        break;
                    }
                    offset += read;
                }
            }
            logOffset += toRead;
            updateConnectionState(new String(buffer, StandardCharsets.UTF_8));
        } catch (IOException e) {
            EnigmaClient.LOGGER.debug("Sidecar-Konsole konnte nicht gelesen werden: {}", e.toString());
        }
    }

    private void updateConnectionState(String chunk) {
        boolean hasMarker = chunk.contains(MARK_CONNECTED)
                || chunk.contains(MARK_LOST)
                || chunk.contains(MARK_ATTEMPT)
                || chunk.contains(MARK_REJECTED);
        if (!hasMarker) {
            return;
        }
        int connected = chunk.lastIndexOf(MARK_CONNECTED);
        int lost = -1;
        for (String marker : new String[]{MARK_LOST, MARK_ATTEMPT, MARK_REJECTED}) {
            lost = Math.max(lost, chunk.lastIndexOf(marker));
        }
        boolean isConnected = connected > lost;
        if (isConnected == wasConnected) {
            return;
        }
        wasConnected = isConnected;
        if (isConnected) {
            connectedSinceMs = System.currentTimeMillis();
            EnigmaClient.notifyUser(
                    "Compute-Host mit World Host verbunden (" + EnigmaClient.config.target() + ")", true);
        } else {
            connectedSinceMs = 0L;
            stats = null;
            nextStatsAtMs = 0L;
            EnigmaClient.notifyUser("Verbindung zum World Host verloren - wird erneut versucht", true);
        }
    }

    /**
     * Fragt den Sidecar per RCON (Serverbefehl {@code enigma distributed status}) live nach
     * Regionen, Leases und Migrationen. Bei Fehlern Backoff von {@link #STATS_BACKOFF_MS}; die
     * Log-Marker-Auswertung bleibt als Fallback bestehen.
     */
    private void pollStats(long now) {
        EnigmaConfig config = EnigmaClient.config;
        if (config == null) {
            nextStatsAtMs = now + STATS_BACKOFF_MS;
            return;
        }
        nextStatsAtMs = now + STATS_INTERVAL_MS;
        try {
            String raw = RconClient.execute(
                    "127.0.0.1", RC_PORT, config.rconPassword, "enigma distributed status", RC_TIMEOUT_MS);
            DistributedStatus parsed = DistributedStatus.parseStatus(raw);
            if (parsed == null) {
                stats = null;
                return;
            }
            if (parsed.migrationsActive > 0) {
                try {
                    String migrations = RconClient.execute(
                            "127.0.0.1", RC_PORT, config.rconPassword, "enigma distributed migrations", 2000);
                    parsed.migrationsDetail = DistributedStatus.parseMigrations(migrations);
                } catch (IOException ignored) {
                }
            }
            stats = parsed;
        } catch (IOException e) {
            stats = null;
            nextStatsAtMs = now + STATS_BACKOFF_MS;
            EnigmaClient.LOGGER.debug("RCON-Statistikabruf fehlgeschlagen: {}", e.toString());
        }
    }

    private Path resolveJar(EnigmaConfig config) {
        String custom = config.jarPath;
        if (custom != null && !custom.isBlank()) {
            Path path = Path.of(custom.trim());
            return path.isAbsolute() ? path : FabricLoader.getInstance().getGameDir().resolve(path);
        }
        Path primary = dir.resolve("EnigmaEngine.jar");
        if (Files.isRegularFile(primary)) {
            return primary;
        }
        Path gameDir = FabricLoader.getInstance().getGameDir();
        for (String candidate : new String[]{
                "../serverJar/EnigmaEngine.jar",
                "../../serverJar/EnigmaEngine.jar"}) {
            Path path = gameDir.resolve(candidate).normalize();
            if (Files.isRegularFile(path)) {
                return path;
            }
        }
        return primary;
    }

    private void prepareDir() throws IOException {
        Files.createDirectories(dir);
        Path eula = dir.resolve("eula.txt");
        if (!Files.exists(eula)) {
            Files.writeString(eula, "eula=true\n");
        }
        Path properties = dir.resolve("server.properties");
        if (!Files.exists(properties)) {
            Files.writeString(properties, SERVER_PROPERTIES);
        }
        configureRcon(properties);
        writeEngineYmlIfMissing();
    }

    /**
     * Schreibt/aktualisiert die RCON-Eintr\u00e4ge in server.properties (enable-rcon, rcon.port,
     * rcon.password) und beh\u00e4lt dabei alle anderen Zeilen unangetastet.
     */
    private void configureRcon(Path properties) throws IOException {
        EnigmaConfig config = EnigmaClient.config;
        if (config == null) {
            return;
        }
        Map<String, String> values = new LinkedHashMap<>();
        List<String> order = new ArrayList<>();
        for (String line : Files.readAllLines(properties)) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                continue;
            }
            int eq = trimmed.indexOf('=');
            if (eq < 0) {
                continue;
            }
            String key = trimmed.substring(0, eq).trim();
            values.put(key, trimmed.substring(eq + 1).trim());
            order.add(key);
        }
        values.put("enable-rcon", "true");
        values.put("rcon.port", String.valueOf(RC_PORT));
        values.put("rcon.password", config.rconPassword);
        StringBuilder out = new StringBuilder();
        for (String key : values.keySet()) {
            out.append(key).append('=').append(values.get(key)).append('\n');
        }
        Files.writeString(properties, out.toString(), StandardCharsets.UTF_8);
    }

    /**
     * Schreibt einmalig eine beschreibbare config/enigma-engine.yml f\u00fcr den Sidecar. Die
     * modseitig gesetzten -D-Overrides bleiben autoritativ; die Datei dient der Sichtbarkeit und
     * manuellen Feineinstellung vor Ort.
     */
    private void writeEngineYmlIfMissing() throws IOException {
        EnigmaConfig config = EnigmaClient.config;
        Path yml = dir.resolve("config/enigma-engine.yml");
        if (Files.exists(yml)) {
            return;
        }
        Files.createDirectories(yml.getParent());
        Files.writeString(yml, engineYmlTemplate(config), StandardCharsets.UTF_8);
    }

    private static String engineYmlTemplate(EnigmaConfig config) {
        return """
                # -----------------------------------------------
                #  EnigmaEngine distributed runtime configuration
                # -----------------------------------------------
                #  Erstellt von EnigmaClient (Compute-Host Sidecar).
                #  Der Client startet den Prozess mit autoritativen -Denigma.distributed.*
                #  Werten; diese Datei kann trotzdem lokal angepasst werden.
                # -----------------------------------------------

                enabled: false
                role: COMPUTE_HOST
                worldHost: %1$s
                port: %2$d
                worldHostPort: %2$d
                identityKey: config/enigma_identity.key

                leaseTtlSeconds: 5
                leaseRenewalIntervalSeconds: 2
                snapshotChunkSizeKb: 64
                maxSnapshotSizeMb: 512
                autoMigrate: true
                autoMigrateIntervalSeconds: 10
                autoMigratePerRun: 2
                autoMigrateMaxConcurrent: 3
                autoMigrateMinChunks: 100
                debugLogging: %3$s
                """.formatted(config.host, config.port, config.debugLogging ? "true" : "false");
    }

    private void setError(String message) {
        lastError = message;
        if (!message.equals(lastNotifiedError)) {
            lastNotifiedError = message;
            EnigmaClient.notifyUser("Compute-Host: " + message, true);
        }
    }

    private void notifyError() {
        if (lastError != null && !lastError.equals(lastNotifiedError)) {
            lastNotifiedError = lastError;
            EnigmaClient.notifyUser("Compute-Host: " + lastError, true);
        }
    }

    private static String javaBinary() {
        String binary = isWindows() ? "java.exe" : "java";
        return Path.of(System.getProperty("java.home")).resolve("bin").resolve(binary).toString();
    }

    private static boolean isWindows() {
        return System.getProperty("os.name", "").toLowerCase(Locale.ROOT).contains("win");
    }

    private static void sendStop(Process target) {
        try {
            target.getOutputStream().write("stop\n".getBytes(StandardCharsets.UTF_8));
            target.getOutputStream().flush();
        } catch (IOException ignored) {
        }
    }

    private static boolean waitForQuietly(Process target, long millis) {
        try {
            return target.waitFor(millis, TimeUnit.MILLISECONDS);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return !target.isAlive();
        }
    }

    private static void destroyTree(Process target, boolean forcibly) {
        target.descendants().forEach(handle -> {
            if (forcibly) {
                handle.destroyForcibly();
            } else {
                handle.destroy();
            }
        });
        if (forcibly) {
            target.destroyForcibly();
        } else {
            target.destroy();
        }
    }

    private static void skipFully(InputStream in, long count) throws IOException {
        long remaining = count;
        while (remaining > 0) {
            long skipped = in.skip(remaining);
            if (skipped <= 0) {
                break;
            }
            remaining -= skipped;
        }
    }
}
